---
data-path: "../data/"
manager:
  db:
    ip: "localhost"
    port: 27017
    username: "admin"
    pass: "admin"
    db_name: "test_course_notify"
  collection:
    fh:
      course: "fh_course"
      watcher: "fh_watcher"
    da:
      course: "da_course"
      watcher: "da_watcher"
  email:
    username: "coursenotify.da@gmail.com"
    pass: "tghxajovxmtxxuhf"
