---
data-path: "../data/"
host-url: ""
debug: false
manager:
  db:
    ip: ""
    port:
    username: ""
    pass: ""
    selectionTimeout: 500
    db_name: ""
  collection:
    fh:
      course: ""
      watcher: ""
    da:
      course: ""
      watcher: ""
email:
  username: ""
  pass: ""
  template:
    dir: "template"
    notify: "notify_email.html"
    confirm: "confirmation_email.html"
