---
data-path: "../data/"
manager:
  db:
    ip: ""
    port:
    username: ""
    pass: ""
    db_name: ""
  collection:
    fh:
      course: ""
      watcher: ""
    da:
      course: ""
      watcher: ""
  email:
    username: ""
    pass: ""
